In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("seattle-weather - seattle-weather.csv")
df

            date  precipitation  temp_max  temp_min  wind  weather
0     2012-01-01            0.0      12.8       5.0   4.7  drizzle
1     2012-01-02           10.9      10.6       2.8   4.5     rain
2     2012-01-03            0.8      11.7       7.2   2.3     rain
3     2012-01-04           20.3      12.2       5.6   4.7     rain
4     2012-01-05            1.3       8.9       2.8   6.1     rain
...          ...            ...       ...       ...   ...      ...
1456  2015-12-27            8.6       4.4       1.7   2.9     rain
1457  2015-12-28            1.5       5.0       1.7   1.3     rain
1458  2015-12-29            0.0       7.2       0.6   2.6      fog
1459  2015-12-30            0.0       5.6      -1.0   3.4      sun
1460  2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]

In [3]:
df["temp_max"].max()

35.6

In [6]:
df['temp_min'].min()

-7.1

In [7]:
df['date'][df['weather']=='rain']

1       2012-01-02
2       2012-01-03
3       2012-01-04
4       2012-01-05
5       2012-01-06
           ...
1452    2015-12-23
1453    2015-12-24
1454    2015-12-25
1456    2015-12-27
1457    2015-12-28
Name: date, Length: 641, dtype: object

In [11]:
df['date'][df['weather']=='sun']

7       2012-01-08
10      2012-01-11
11      2012-01-12
12      2012-01-13
32      2012-02-02
           ...
1427    2015-11-28
1443    2015-12-14
1455    2015-12-26
1459    2015-12-30
1460    2015-12-31
Name: date, Length: 640, dtype: object

In [12]:
df['wind'].mean()

3.24113620807666

In [13]:
df['precipitation'].max()

55.9

In [14]:
df[1:30]

          date  precipitation  temp_max  temp_min  wind  weather
1   2012-01-02           10.9      10.6       2.8   4.5     rain
2   2012-01-03            0.8      11.7       7.2   2.3     rain
3   2012-01-04           20.3      12.2       5.6   4.7     rain
4   2012-01-05            1.3       8.9       2.8   6.1     rain
5   2012-01-06            2.5       4.4       2.2   2.2     rain
6   2012-01-07            0.0       7.2       2.8   2.3     rain
7   2012-01-08            0.0      10.0       2.8   2.0      sun
8   2012-01-09            4.3       9.4       5.0   3.4     rain
9   2012-01-10            1.0       6.1       0.6   3.4     rain
10  2012-01-11            0.0       6.1      -1.1   5.1      sun
11  2012-01-12            0.0       6.1      -1.7   1.9      sun
12  2012-01-13            0.0       5.0      -2.8   1.3      sun
13  2012-01-14            4.1       4.4       0.6   5.3     snow
14  2012-01-15            5.3       1.1      -3.3   3.2     snow
15  2012-01-16            2.5       1.7      -2.8   5.0     snow
16  2012-01-17            8.1       3.3       0.0   5.6     snow
17  2012-01-18           19.8       0.0      -2.8   5.0     snow
18  2012-01-19           15.2      -1.1      -2.8   1.6     snow
19  2012-01-20           13.5       7.2      -1.1   2.3     snow
20  2012-01-21            3.0       8.3       3.3   8.2     rain
21  2012-01-22            6.1       6.7       2.2   4.8     rain
22  2012-01-23            0.0       8.3       1.1   3.6     rain
23  2012-01-24            8.6      10.0       2.2   5.1     rain
24  2012-01-25            8.1       8.9       4.4   5.4     rain
25  2012-01-26            4.8       8.9       1.1   4.8     rain
26  2012-01-27            0.0       6.7      -2.2   1.4  drizzle
27  2012-01-28            0.0       6.7       0.6   2.2     rain
28  2012-01-29           27.7       9.4       3.9   4.5     rain
29  2012-01-30            3.6       8.3       6.1   5.1     rain

In [15]:
df.columns

Index(['date', 'precipitation', 'temp_max', 'temp_min', 'wind', 'weather'], dtype='object')

In [16]:
df.date

0       2012-01-01
1       2012-01-02
2       2012-01-03
3       2012-01-04
4       2012-01-05
           ...
1456    2015-12-27
1457    2015-12-28
1458    2015-12-29
1459    2015-12-30
1460    2015-12-31
Name: date, Length: 1461, dtype: object

In [17]:
df.wind

0       4.7
1       4.5
2       2.3
3       4.7
4       6.1
       ...
1456    2.9
1457    1.3
1458    2.6
1459    3.4
1460    3.5
Name: wind, Length: 1461, dtype: float64

In [19]:
df['date']

0       2012-01-01
1       2012-01-02
2       2012-01-03
3       2012-01-04
4       2012-01-05
           ...
1456    2015-12-27
1457    2015-12-28
1458    2015-12-29
1459    2015-12-30
1460    2015-12-31
Name: date, Length: 1461, dtype: object

In [20]:
df['temp_max'].describe()

count    1461.000000
mean       16.439083
std         7.349758
min        -1.600000
25%        10.600000
50%        15.600000
75%        22.200000
max        35.600000
Name: temp_max, dtype: float64

In [22]:
df[df.temp_max==df.temp_max.max()]

           date  precipitation  temp_max  temp_min  wind weather
953  2014-08-11            0.5      35.6      17.8   2.6    rain

In [23]:
df.date[df.temp_max==df.temp_max.max()]

953    2014-08-11
Name: date, dtype: object

In [24]:
df.wind[df.temp_max==df.temp_max.max()]

953    2.6
Name: wind, dtype: float64

In [3]:
import pandas as pd

In [4]:
df1=pd.read_excel("Book.xlsx")
df1

,Employee_ID,YearsExperience,Current_Salary,Last_Year_Salary:,Salary_Increase
0,501,1.1,39343,30000,9343
1,502,1.3,46205,39000,7205
2,503,1.5,37731,29000,8731
3,504,2.0,43525,33000,10525
4,505,2.2,39891,23000,16891
5,506,2.9,56642,35000,21642
6,507,3.0,60150,37000,23150
7,508,3.2,67000,47000,20000
8,509,3.2,64445,50000,14445
9,510,3.7,64678,50000,14678
10,511,3.9,63218,45000,18218
11,512,4.0,77345,45000,32345
12,513,4.0,72000,44000,28000
13,514,10.5,175000,67000,108000
14,515,4.5,61111,35000,26111
15,516,4.9,80005,52500,27505
16,517,5.1,86029,56782,29247
17,518,5.3,103088,72567,30521
18,519,5.9,81363,59079,22284
19,520,6.0,123940,78999,44941
20,521,6.8,131738,80993,50745
21,522,7.1,148273,88888,59385
22,523,7.9,131302,91324,39978
23,524,8.2,153812,99999,53813
24,525,8.7,169431,102009,67422
25,526,9.0,175582,95678,79904
26,527,9.5,196969,100234,96735
27,528,9.6,202635,99678,102957
28,529,10.3,192391,80955,111436
29,530,10.1,211872,100000,111872